// Erico products
export const ericoProducts = [
  {
    id: 3001,
    name: "PBCR Braided Power Shunts",
    brand: "ERICO",
    category: "Flexible Conductors",
    description: "Material: Copper, Wire Diameter: 0.15 mm. When used in parallel, the two shunts must be spaced with a minimum distance equal to the thickness of the shunt to allow air cooling.",
    rating: 4.7,
    reviews: 23,
    images: ["/assets/images/products/erico/PBCR_braided_power_shunts_PBCR_braided_power_shunt_PBCR-power-shunt-350x360_d70d3343.jpg"],
    inStock: true,
    specs: ["Copper Material", "0.15mm Wire Diameter", "Power Shunt", "Parallel Compatible"],
    url: "https://www.westshorecontrols.com/product/pbcr-braided-power-shunts/"
  },
  {
    id: 3002,
    name: "Threaded Bar TCB 12 x 5 x 1000",
    model: "TCB12X5-1M",
    sku: "549220",
    brand: "ERICO",
    category: "Busbars",
    description: "Copper threaded bar with 12mm width, 5mm thickness, and 1000mm length. Features M5 thread size with standard packaging of 4 pieces.",
    price: 42,
    rating: 4.6,
    reviews: 34,
    images: ["/assets/images/products/erico/TCB_threaded_busbar_TCB_threaded_busbar_TCB_threaded_busbar-350x360_52c7809c.jpg"],
    inStock: true,
    specs: ["12mm Width", "5mm Thickness", "1000mm Length", "M5 Thread", "Copper Material"],
    url: "https://www.westshorecontrols.com/product/threaded-bar-tcb-12-x-5-x-1000/"
  },
  {
    id: 3003,
    name: "Neutral Bars",
    brand: "ERICO",
    category: "Distribution Blocks",
    description: "Neutral bars for electrical distribution applications. Available in different amperage ratings including 125A and 160A configurations.",
    rating: 4.5,
    reviews: 18,
    images: ["/assets/images/products/erico/UD-80A_distribution_blocks_UD-80A_distribution_blo_UD-80A-300x300_559cda7a.jpg"],
    inStock: true,
    specs: ["125A/160A Ratings", "Neutral Bar", "Distribution Block"],
    url: "https://www.westshorecontrols.com/product/neutral-bars/"
  },
  {
    id: 3004,
    name: "RFS Reinforced ERICO FLEXIBAR Support",
    brand: "ERICO",
    category: "Busbar Supports",
    description: "Reinforced support system for ERICO FLEXIBAR applications, providing enhanced mechanical stability and reliability.",
    rating: 4.8,
    reviews: 12,
    images: ["/assets/images/products/erico/compact_reinforced_busbar_supports_compact_reinfor_compact-reinforced-busbar-supports-300x300_44abd210.jpg"],
    inStock: true,
    specs: ["Reinforced Design", "FLEXIBAR Compatible", "Mechanical Support"],
    url: "https://www.westshorecontrols.com/product/rfs-reinforced-erico-flexibar-support/"
  },
  {
    id: 3005,
    name: "SBTT Power Terminals",
    brand: "ERICO",
    category: "Power Terminals",
    description: "Power terminals designed for high-current electrical connections with reliable performance and durability.",
    rating: 4.7,
    reviews: 25,
    images: ["/assets/images/products/erico/SB-power-terminals_SB-power-terminals_SB-power-terminals-300x300_81ee0a3c.jpg"],
    inStock: true,
    specs: ["Power Terminal", "High Current", "Reliable Connection"],
    url: "https://www.westshorecontrols.com/product/sbtt-power-terminals/"
  },
  {
    id: 3006,
    name: "FC ERIFLEX FLEXIBAR Clamp",
    brand: "ERICO",
    category: "Connecting Clamps",
    description: "Steel clamp with electrogalvanized finish, quality class 8.8, 20mm clamping capacity for FLEXIBAR to busbar connections.",
    rating: 4.6,
    reviews: 31,
    images: ["/assets/images/products/erico/FC_erico_flexibar_clamp_FC_erico_flexibar_clamp_FC_erico_flexibar_clamp-350x360_8175290c.jpg"],
    inStock: true,
    specs: ["Steel Material", "Electrogalvanized", "20mm Capacity", "Quality Class 8.8"],
    url: "https://www.westshorecontrols.com/product/fc-erico-flexibar-to-busbar-clamp/"
  },
  {
    id: 3007,
    name: "TCB Threaded Busbar x 2/4 x 1000mm",
    brand: "ERICO",
    category: "Busbars",
    description: "Copper threaded busbar available in various widths and thicknesses. Standard length 1000mm with M5/M8 thread sizes.",
    rating: 4.8,
    reviews: 22,
    images: ["/assets/images/products/erico/TCBW_threaded_busbar_TCBW_threaded_busbar_TCBW_threaded_busbar-350x360_ac477da4.jpg"],
    inStock: true,
    specs: ["Copper Material", "Various Widths", "1000mm Length", "M5/M8 Threads"],
    url: "https://www.westshorecontrols.com/product/tcb-threaded-busbar/"
  },
  {
    id: 3008,
    name: "Universal Busbar Supports",
    brand: "ERICO",
    category: "Busbar Supports",
    description: "Universal mounting supports for busbar installations, providing flexible and reliable mounting solutions.",
    rating: 4.5,
    reviews: 19,
    images: ["/assets/images/products/erico/UBS_Universal_Busbar_Supports_UBS_Universal_Busbar_UBS-300x300_3b919330.jpg"],
    inStock: true,
    specs: ["Universal Design", "Flexible Mounting", "Busbar Support"],
    url: "https://www.westshorecontrols.com/product/universal-busbar-supports/"
  },
  {
    id: 3009,
    name: "QCC ERIFLEX FLEXIBAR Clamps",
    brand: "ERICO",
    category: "Connecting Clamps",
    description: "Steel clamps with electrogalvanized finish for conductor widths 6.0-13.0mm, featuring reliable connection performance.",
    rating: 4.7,
    reviews: 16,
    images: ["/assets/images/products/erico/QCC_clamps_eriflex_flexibar_QCC_clamps_eriflex_fle_QCC_clamp_eriflex_flexibar-350x360_d1ce38fb.jpg"],
    inStock: true,
    specs: ["6.0-13.0mm Width", "Steel Construction", "Electrogalvanized"],
    url: "https://www.westshorecontrols.com/product/qcc-erico-flexibar-clamp/"
  },
  {
    id: 3010,
    name: "Adjustable Busbar Support",
    brand: "ERICO",
    category: "Busbar Supports",
    description: "Adjustable support system for busbar installations, allowing flexible positioning and secure mounting.",
    rating: 4.6,
    reviews: 14,
    images: ["/assets/images/products/erico/adjustable_busbar_supports_adjustable_busbar_suppo_adjustable-busbar-supports-300x300_152ba74f.jpg"],
    inStock: true,
    specs: ["Adjustable Design", "Flexible Positioning", "Secure Mounting"],
    url: "https://www.westshorecontrols.com/product/adjustable-busbar-support/"
  },
  {
    id: 3011,
    name: "Threaded Bar TCB 20 x 5 x 1000",
    model: "TCB20X5-1M",
    sku: "550220",
    brand: "ERICO",
    category: "Busbars",
    description: "Copper threaded bar 20mm width, 5mm thickness, 1000mm length with M6 thread size. Standard packaging quantity 4 pieces.",
    price: 77,
    rating: 4.8,
    reviews: 28,
    images: ["/assets/images/products/erico/TCB_threaded_busbar_with_fixing_hole_TCB_threaded__TCB_threaded_busbar_with_fixing_hole-350x360_211e081e.jpg"],
    inStock: true,
    specs: ["20mm Width", "5mm Thickness", "1000mm Length", "M6 Thread", "Copper Material"],
    url: "https://www.westshorecontrols.com/product/threaded-bar-tcb-20-x-5-x-1000/"
  },
  {
    id: 3012,
    name: "ERICO FLEXIBAR",
    brand: "ERICO",
    category: "Flexible Conductors",
    description: "Flexible wire replacement with electrolytic copper conductor and high-resistance vinyl compound insulation. Working temperature range -25°C to 105°C.",
    rating: 4.9,
    reviews: 45,
    images: ["/assets/images/products/erico/Flexible_Conductors_flexible-conductor_98144139.jpg"],
    inStock: true,
    specs: ["Cu-ETP Conductor", "Vinyl Insulation", "-25°C to 105°C", "370% Elongation"],
    url: "https://www.westshorecontrols.com/product/eriflex-flexibar-flexible-wire-replacement/"
  },
  {
    id: 3013,
    name: "MBJ Grounding and Bonding Braid",
    brand: "ERICO",
    category: "Flexible Conductors",
    description: "Tinned copper grounding and bonding braid with complete range from 6-100 mm² cross section and 100-500mm lengths. Available with or without tinned copper lugs.",
    rating: 4.7,
    reviews: 33,
    images: ["/assets/images/products/erico/MBJ_grounding_bonding_braids_erico_MBJ_grounding_b_MBJ-grounding-bonding-braids-350x360_80fa7804.jpg"],
    inStock: true,
    specs: ["6-100 mm² Cross Section", "100-500mm Lengths", "Tinned Copper", "Grounding/Bonding"],
    url: "https://www.westshorecontrols.com/product/mbj-grounding-and-bonding-braid-tinned-copper/"
  },
  {
    id: 3014,
    name: "IBS Flat Insulated Braided Conductor",
    brand: "ERICO",
    category: "Flexible Conductors",
    description: "Suitable for all main electrical devices. Resistant to vibration, improving reliability and performance. Quick and easy installation with improved assembly flexibility.",
    rating: 4.6,
    reviews: 27,
    images: ["/assets/images/products/erico/IBS_Flat_Insulated_Braided_Conductor_IBS-conductor_IBS-conductor_ec75339b.jpg"],
    inStock: true,
    specs: ["Vibration Resistant", "Easy Installation", "Assembly Flexible", "Insulated Design"],
    url: "https://www.westshorecontrols.com/product/insulated-braided-conductor-ibs/"
  },
  {
    id: 3015,
    name: "ISO-TP Low Voltage Metric Insulators",
    brand: "ERICO",
    category: "Insulators",
    description: "CE Conformity and RoHS compliance insulators with IEC compliance and UL recognition. Dielectric withstand rating of 1500 Vac/Vdc.",
    rating: 4.8,
    reviews: 21,
    images: ["/assets/images/products/erico/ISO-TP_low_voltage_metric_insulators_ISO-TP_low_vo_ISO-TP-insulators-300x300_f859f294.jpg"],
    inStock: true,
    specs: ["CE Conformity", "RoHS Compliant", "1500 Vac/Vdc Rating", "UL Recognized"],
    url: "https://www.westshorecontrols.com/product/iso-tp-low-voltage-metric-insulators/"
  },
  {
    id: 3016,
    name: "40A Two and Four Pole Distribution Block",
    brand: "ERICO",
    category: "Distribution Blocks",
    description: "Distribution blocks rated for 40A applications in both two-pole and four-pole configurations.",
    rating: 4.5,
    reviews: 24,
    images: ["/assets/images/products/erico/BD-40A_BD-40A_BD-40A-300x300_36e975cb.jpg"],
    inStock: true,
    specs: ["40A Rating", "2-Pole/4-Pole", "Distribution Block"],
    url: "https://www.westshorecontrols.com/product/40-a-two-and-four-pole-distribution-block/"
  },
  {
    id: 3017,
    name: "Connector XM5 for 12 x 4 Threaded Busbar",
    brand: "ERICO",
    category: "Connectors",
    description: "Copper connector designed specifically for 12 x 4 threaded busbar connections. Standard packaging quantity 100 pieces.",
    rating: 4.7,
    reviews: 15,
    images: ["/assets/images/products/erico/XM5_threaded_busbar_connector_XM5_threaded_busbar__XM5_connector-350x360_80d380c4.jpg"],
    inStock: true,
    specs: ["Copper Material", "12 x 4 Compatible", "100pc Packaging"],
    url: "https://www.westshorecontrols.com/product/xm5-threaded-busbar-connector/"
  },
  {
    id: 3018,
    name: "PCB Plain Busbars",
    brand: "ERICO",
    category: "Busbars",
    description: "Plain copper busbars designed for PCB applications, providing reliable electrical connections in circuit board designs.",
    rating: 4.6,
    reviews: 18,
    images: ["/assets/images/products/erico/PCB_plain_copper_busbar_PCB_plain_copper_busbar_PBC_plain_busbar-350x360_b933d97c.jpg"],
    inStock: true,
    specs: ["Plain Copper", "PCB Application", "Circuit Board Design"],
    url: "https://www.westshorecontrols.com/product/pcb-plain-copper-busbar/"
  },
  {
    id: 3019,
    name: "Compact and Adjustable Busbar Supports (CABS)",
    brand: "ERICO",
    category: "Busbar Supports",
    description: "Supports for panels 300-800mm, bars 30-125mm, thickness 5 or 10mm. Rated from 400A up to 4500A.",
    rating: 4.8,
    reviews: 20,
    images: ["/assets/images/products/erico/Compact_and_Adjustable_Busbar_Support_Compact_and__CABS-300x300_ceb023d5.jpg"],
    inStock: true,
    specs: ["300-800mm Panels", "30-125mm Bars", "400A-4500A Rating", "5/10mm Thickness"],
    url: "https://www.westshorecontrols.com/product/compact-and-adjustable-busbar-supports-cabs/"
  },
  {
    id: 3020,
    name: "80/100A Two and Four Pole Distribution Block",
    brand: "ERICO",
    category: "Distribution Blocks",
    description: "Distribution blocks rated for 80/100A applications available in both two-pole and four-pole configurations with aluminum options.",
    rating: 4.7,
    reviews: 26,
    images: ["/assets/images/products/erico/UDJ-125A_UDJ-125A_UDJ-125A-300x300_45b4a162.jpg"],
    inStock: true,
    specs: ["80/100A Rating", "2-Pole/4-Pole", "Aluminum Options"],
    url: "https://www.westshorecontrols.com/product/80100-a-two-and-four-pole-distribution-block/"
  },
  {
    id: 3021,
    name: "ERIFLEX ZIPFLEX, FGBS & SBS Cabling Sleeves",
    brand: "ERICO",
    category: "Cable Management",
    description: "Comprehensive range of cabling sleeves including ZIPFLEX (polypropylene), FGBS (glass fiber braided), and SBS (silicone). Temperature ranges from -70°C to 400°C depending on type.",
    rating: 4.6,
    reviews: 18,
    images: ["/assets/images/products/erico/FGBS_FGBS_FGBS-300x300_2cd174d2.jpg"],
    inStock: true,
    specs: ["Multiple Materials", "-70°C to 400°C", "Halogen Free", "UL Approved"],
    url: "https://www.westshorecontrols.com/product/eriflex-zipflex-fgbs-sbs/"
  },
  {
    id: 3022,
    name: "PDBS & ERIFLEX SPIRFLEX Cabling Sleeves",
    brand: "ERICO",
    category: "Cable Management",
    description: "Polyamide braided sleeves (PDBS) and spiral sleeves (SPIRFLEX). Highly expandable, provides complete wire coverage up to Ø 80mm. Available in grey or black.",
    rating: 4.5,
    reviews: 14,
    images: ["/assets/images/products/erico/PDBS_cabling_sleeves_PDBS_cabling_sleeves_PDBS-cabling-sleeves-300x300_551b6613.jpg"],
    inStock: true,
    specs: ["Polyamide 6/6", "Expandable to Ø 80mm", "Halogen Free", "2 Colors Available"],
    url: "https://www.westshorecontrols.com/product/cabling-sleeves-pdbs-eriflex-spirflex/"
  },
  {
    id: 3023,
    name: "TTCE Tinned Copper Tubular Braids",
    brand: "ERICO",
    category: "Cable Management",
    description: "Tinned copper tubular braids for cable management and EMI/EMC shielding applications. Excellent conductivity and corrosion resistance.",
    rating: 4.7,
    reviews: 21,
    images: ["/assets/images/products/erico/FTCB_flat_tinned_copper_braids_FTCB_flat_tinned_co_FTCB-flat-tinned-copper-braids-350x360_e792609d.jpg"],
    inStock: true,
    specs: ["Tinned Copper", "Tubular Design", "EMI/EMC Shielding", "Corrosion Resistant"],
    url: "https://www.westshorecontrols.com/product/ttce-tinned-copper-tubular-braid/"
  },
  {
    id: 3024,
    name: "FBC ERICO FLEXIBAR Cable to Busbar Clamp",
    brand: "ERICO",
    category: "Cable Management",
    description: "Steel connectors for connecting cables to busbars without drilling. Available for 5mm and 10mm busbar thickness with various conductor sizes.",
    rating: 4.8,
    reviews: 29,
    images: ["/assets/images/products/erico/FBC_connectors_for_connecting_without_drilling_FBC_FBC_connectors_without_drilling-350x360_fe8d240e.jpg"],
    inStock: true,
    specs: ["Steel Construction", "Electrogalvanized", "No Drilling Required", "Multiple Sizes"],
    url: "https://www.westshorecontrols.com/product/fbc-erico-flexibarcable-to-busbar-clamp/"
  }
]; 